### PR TITLE
Added our miniproject

### PR DESCRIPTION
**Pull request by oishish**
If you would like to add Jae, Sonny, and I's miniproject on the Thomas Algorithm to the repo, here it is. Thank you!

### CODE REVIEW

**Comment by cortner** [comment]
thanks a lot for this PR!

**Comment by cortner** [comment]
It looks like you've removed all output from the notebook, correct?

**Comment by oishish** [comment]
That was a mistake, added outputs.

**Comment by cortner** [comment]
no no not at all - I want the outputs removed, just wanted to confirm that I didn't miss anything.

**Comment by oishish** [comment]
Oops, then I will revert that last commit

**Pull request merged**
